version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /.docker-config/rabbitmq/data:/var/lib/rabbitmq/
      - /.docker-config/rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge
